var json_AlfaRomeo_14 = {
"type": "FeatureCollection",
"name": "AlfaRomeo_14",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "REIMS" }, "geometry": { "type": "Point", "coordinates": [ 4.0832, 49.2355 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SAINT-ETIENNE" }, "geometry": { "type": "Point", "coordinates": [ 4.4096, 45.4556 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "CESSON-SEVIGNE" }, "geometry": { "type": "Point", "coordinates": [ -1.5977, 48.1138 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "VILLENEUVE D'ASCQ" }, "geometry": { "type": "Point", "coordinates": [ 3.1213, 50.633 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "PERPIGNAN" }, "geometry": { "type": "Point", "coordinates": [ 2.8928, 42.6726 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BEZIERS" }, "geometry": { "type": "Point", "coordinates": [ 3.2558, 43.3458 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MARSEILLE" }, "geometry": { "type": "Point", "coordinates": [ 5.3902, 43.2751 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "FONTAINE" }, "geometry": { "type": "Point", "coordinates": [ 5.6812, 45.1904 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "TOULON CEDEX 09" }, "geometry": { "type": "Point", "coordinates": [ 5.99, 43.1349 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "NANTERRE" }, "geometry": { "type": "Point", "coordinates": [ 2.2122, 48.8863 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "PARIS" }, "geometry": { "type": "Point", "coordinates": [ 2.4041, 48.8388 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LE CANNET" }, "geometry": { "type": "Point", "coordinates": [ 7.0121, 43.5764 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "TOULOUSE" }, "geometry": { "type": "Point", "coordinates": [ 1.4986, 43.5716 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LIEVIN CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 2.787422, 50.426641 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "AUBIERE" }, "geometry": { "type": "Point", "coordinates": [ 3.1343, 45.7497 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LAXOU" }, "geometry": { "type": "Point", "coordinates": [ 6.1326, 48.6931 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ANNECY" }, "geometry": { "type": "Point", "coordinates": [ 6.1141, 45.8974 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LYON" }, "geometry": { "type": "Point", "coordinates": [ 4.7989, 45.776 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MERIGNAC" }, "geometry": { "type": "Point", "coordinates": [ -0.6724, 44.831 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ORLEANS CEDEX 02" }, "geometry": { "type": "Point", "coordinates": [ 1.9136, 47.8758 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ANNEMASSE" }, "geometry": { "type": "Point", "coordinates": [ 6.2608, 46.1968 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "CHAMBRAY LES TOURS" }, "geometry": { "type": "Point", "coordinates": [ 0.7115, 47.3193 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LEVALLOIS PERRET" }, "geometry": { "type": "Point", "coordinates": [ 2.279, 48.8944 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BOULOGNE BILLANCOURT" }, "geometry": { "type": "Point", "coordinates": [ 2.2454, 48.8432 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ROQUEBRUNE-SUR-ARGENS" }, "geometry": { "type": "Point", "coordinates": [ 6.637, 43.4625 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ARLES CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 4.6422, 43.6647 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MANOSQUE" }, "geometry": { "type": "Point", "coordinates": [ 5.7935, 43.8211 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "CHENOVE" }, "geometry": { "type": "Point", "coordinates": [ 5.0206, 47.2859 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "COLMAR CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 7.3788, 48.0796 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LONS LE SAUNIER" }, "geometry": { "type": "Point", "coordinates": [ 5.5667, 46.6719 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "EVREUX" }, "geometry": { "type": "Point", "coordinates": [ 1.1878, 49.026 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SAINT-OUEN-L'AUMONE" }, "geometry": { "type": "Point", "coordinates": [ 2.1221, 49.035 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MONTLHERY" }, "geometry": { "type": "Point", "coordinates": [ 2.2699, 48.6434 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "TRELISSAC" }, "geometry": { "type": "Point", "coordinates": [ 0.7571, 45.1883 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ORVAULT" }, "geometry": { "type": "Point", "coordinates": [ -1.6273, 47.2545 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MOUILLERON LE CAPTIF" }, "geometry": { "type": "Point", "coordinates": [ -1.427, 46.7249 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "VANNES CEDEX" }, "geometry": { "type": "Point", "coordinates": [ -2.784059, 47.666086 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LANESTER CEDEX" }, "geometry": { "type": "Point", "coordinates": [ -3.3397, 47.7824 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LESCAR" }, "geometry": { "type": "Point", "coordinates": [ -0.4305, 43.3189 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LA RAVOIRE" }, "geometry": { "type": "Point", "coordinates": [ 5.9692, 45.5632 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BOURGOIN-JALLIEU CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 5.257699, 45.58709 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BISCHHEIM CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 7.7283, 48.6179 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "NIMES CEDEX 9" }, "geometry": { "type": "Point", "coordinates": [ 4.3401, 43.8153 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ORANGE CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 4.8386, 44.1222 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "AJACCIO CEDEX 2" }, "geometry": { "type": "Point", "coordinates": [ 8.7486, 41.9421 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "PETITE FORET" }, "geometry": { "type": "Point", "coordinates": [ 3.4751, 50.3811 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ENGLOS" }, "geometry": { "type": "Point", "coordinates": [ 2.9656, 50.6356 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "VILLEFRANCHE-SUR-SAONE" }, "geometry": { "type": "Point", "coordinates": [ 4.7411, 45.9933 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "CHAMPNIERS" }, "geometry": { "type": "Point", "coordinates": [ 0.1735, 45.6896 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "AYTRE" }, "geometry": { "type": "Point", "coordinates": [ -1.0936, 46.1314 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SAINT-GEORGES-DES-COTEAUX" }, "geometry": { "type": "Point", "coordinates": [ -0.6776, 45.753 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "GROSLAY" }, "geometry": { "type": "Point", "coordinates": [ 2.3593, 48.9897 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "CHAMBOURCY" }, "geometry": { "type": "Point", "coordinates": [ 2.0538, 48.9044 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MAREUIL LES MEAUX" }, "geometry": { "type": "Point", "coordinates": [ 2.8783, 48.9333 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "FRANOIS" }, "geometry": { "type": "Point", "coordinates": [ 5.9398, 47.2157 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ILLZACH CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 7.358, 47.7627 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "CHAVELOT" }, "geometry": { "type": "Point", "coordinates": [ 6.4387, 48.2154 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LE MANS" }, "geometry": { "type": "Point", "coordinates": [ 0.1745, 47.9713 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LIMOGES" }, "geometry": { "type": "Point", "coordinates": [ 1.2785, 45.8889 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "POITIERS" }, "geometry": { "type": "Point", "coordinates": [ 0.34, 46.5903 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ANGERS" }, "geometry": { "type": "Point", "coordinates": [ -0.5328, 47.4489 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MONACO" }, "geometry": { "type": "Point", "coordinates": [ 7.413, 43.7296 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "NEUILLY" }, "geometry": { "type": "Point", "coordinates": [ 2.261, 48.8849 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "CORBEIL ESSONNES" }, "geometry": { "type": "Point", "coordinates": [ 2.456, 48.6081 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "VENISSIEUX CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 4.8545, 45.719 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "NICE" }, "geometry": { "type": "Point", "coordinates": [ 7.1996, 43.6826 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MONTPELLIER CEDEX 3" }, "geometry": { "type": "Point", "coordinates": [ 3.8662, 43.5798 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "NARBONNE" }, "geometry": { "type": "Point", "coordinates": [ 3.0305, 43.1797 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "FURIANI" }, "geometry": { "type": "Point", "coordinates": [ 9.4408, 42.6492 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LONGUENESSE" }, "geometry": { "type": "Point", "coordinates": [ 2.2806, 50.739 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ROUEN" }, "geometry": { "type": "Point", "coordinates": [ 1.0708, 49.4465 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "PARIS" }, "geometry": { "type": "Point", "coordinates": [ 2.3011, 48.8594 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BIEVILLE BEUVILLE" }, "geometry": { "type": "Point", "coordinates": [ -0.3683, 49.2278 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BRUAY-LA-BUISSIERE CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 2.5597, 50.4876 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MACON CEDEX 9" }, "geometry": { "type": "Point", "coordinates": [ 4.8098, 46.2871 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "COIGNIERES" }, "geometry": { "type": "Point", "coordinates": [ 1.9319, 48.7569 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "AIX-EN-PROVENCE CEDEX 4" }, "geometry": { "type": "Point", "coordinates": [ 5.4026, 43.5071 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SAINT-DENIS" }, "geometry": { "type": "Point", "coordinates": [ 2.3388, 48.9154 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ANTONY" }, "geometry": { "type": "Point", "coordinates": [ 2.3032, 48.7467 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "TOULOUSE" }, "geometry": { "type": "Point", "coordinates": [ 1.4176, 43.6608 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "TARBES" }, "geometry": { "type": "Point", "coordinates": [ 0.0419, 43.2362 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BAYONNE CEDEX" }, "geometry": { "type": "Point", "coordinates": [ -1.4949, 43.4664 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BOE" }, "geometry": { "type": "Point", "coordinates": [ 0.6276, 44.1758 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MONTAUBAN" }, "geometry": { "type": "Point", "coordinates": [ 1.3378, 43.9971 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "ONET LE CHÂTEAU" }, "geometry": { "type": "Point", "coordinates": [ 2.5821, 44.3692 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "DAX" }, "geometry": { "type": "Point", "coordinates": [ -1.0551, 43.7202 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SAINT-NAZAIRE CEDEX" }, "geometry": { "type": "Point", "coordinates": [ -2.2708, 47.2576 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "NIORT" }, "geometry": { "type": "Point", "coordinates": [ -0.4221, 46.3366 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MALEMORT-SUR-CORREZE" }, "geometry": { "type": "Point", "coordinates": [ 1.5721, 45.1608 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "QUIMPER" }, "geometry": { "type": "Point", "coordinates": [ -4.0352, 47.983 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BREST CEDEX 2" }, "geometry": { "type": "Point", "coordinates": [ -4.469013, 48.411946 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MABLY ROANNE" }, "geometry": { "type": "Point", "coordinates": [ 4.0731, 46.0748 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "PULNOY" }, "geometry": { "type": "Point", "coordinates": [ 6.2527, 48.7044 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LAVAL" }, "geometry": { "type": "Point", "coordinates": [ -0.7974, 48.084 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "WOIPPY" }, "geometry": { "type": "Point", "coordinates": [ 6.1576, 49.155 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "DECHY" }, "geometry": { "type": "Point", "coordinates": [ 3.1215, 50.344 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "PLERIN" }, "geometry": { "type": "Point", "coordinates": [ -2.7593, 48.5372 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "CHATENOY LE ROYAL" }, "geometry": { "type": "Point", "coordinates": [ 4.8235, 46.7938 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "VINEUIL" }, "geometry": { "type": "Point", "coordinates": [ 1.3677, 47.5831 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "NEUVILLE LES DIEPPE" }, "geometry": { "type": "Point", "coordinates": [ 1.1187, 49.9011 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BOURGES" }, "geometry": { "type": "Point", "coordinates": [ 2.423, 47.0951 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "VARENNES-VAUZELLES" }, "geometry": { "type": "Point", "coordinates": [ 3.1433, 47.0324 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SAINT-MAUR" }, "geometry": { "type": "Point", "coordinates": [ 1.6567, 46.7868 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "L'AIGLE" }, "geometry": { "type": "Point", "coordinates": [ 0.6548, 48.7649 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "THYEZ CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 6.5247, 46.0862 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SAINTE-MARGUERITE" }, "geometry": { "type": "Point", "coordinates": [ 6.9615, 48.2687 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "PONTARLIER" }, "geometry": { "type": "Point", "coordinates": [ 6.3322, 46.9072 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BOURG-EN-BRESSE" }, "geometry": { "type": "Point", "coordinates": [ 5.2443, 46.1881 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "DREUX" }, "geometry": { "type": "Point", "coordinates": [ 1.3482, 48.7472 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LUISANT" }, "geometry": { "type": "Point", "coordinates": [ 1.4552, 48.4167 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BEAUVAIS" }, "geometry": { "type": "Point", "coordinates": [ 2.1185, 49.4108 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SAINT-MAXIMIN" }, "geometry": { "type": "Point", "coordinates": [ 2.4654, 49.2322 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SOISSONS" }, "geometry": { "type": "Point", "coordinates": [ 3.3059, 49.3816 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "AMILLY" }, "geometry": { "type": "Point", "coordinates": [ 2.73508, 47.962667 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "CHAMPLAY" }, "geometry": { "type": "Point", "coordinates": [ 3.4493, 47.9567 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "BARBEREY-SAINT-SULPICE" }, "geometry": { "type": "Point", "coordinates": [ 4.0241, 48.3294 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SAINT-QUENTIN" }, "geometry": { "type": "Point", "coordinates": [ 3.656, 49.5787 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LAON" }, "geometry": { "type": "Point", "coordinates": [ 3.6574, 49.5802 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "CHENNEVIERES SUR MARNE" }, "geometry": { "type": "Point", "coordinates": [ 2.5386, 48.8027 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "VERT SAINT DENIS" }, "geometry": { "type": "Point", "coordinates": [ 2.6312, 48.5652 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "LE PONTET" }, "geometry": { "type": "Point", "coordinates": [ 4.8578, 43.9753 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "SALON DE PROVENCE CEDEX" }, "geometry": { "type": "Point", "coordinates": [ 5.0945, 43.6191 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "MONTELIMAR" }, "geometry": { "type": "Point", "coordinates": [ 4.7439, 44.5258 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "VITROLLES" }, "geometry": { "type": "Point", "coordinates": [ 5.2713, 43.4216 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "GAP" }, "geometry": { "type": "Point", "coordinates": [ 6.0442, 44.5104 ] } },
{ "type": "Feature", "properties": { "Make": "Alfa-Romeo", "City": "VALENCE" }, "geometry": { "type": "Point", "coordinates": [ 4.9376, 44.9202 ] } }
]
}
