var json_Jaguar_9 = {
"type": "FeatureCollection",
"name": "Jaguar_9",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Le Cannet" }, "geometry": { "type": "Point", "coordinates": [ 7.01234, 43.57559 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Merignac" }, "geometry": { "type": "Point", "coordinates": [ -0.6703392, 44.844963 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Perpignan" }, "geometry": { "type": "Point", "coordinates": [ 2.8973905, 42.6724591 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Limonest" }, "geometry": { "type": "Point", "coordinates": [ 4.77356, 45.80411 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "V�nissieux" }, "geometry": { "type": "Point", "coordinates": [ 4.8652926, 45.717525 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "CHANTILLY" }, "geometry": { "type": "Point", "coordinates": [ 2.463, 49.2 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Loire Atlantique" }, "geometry": { "type": "Point", "coordinates": [ -1.6228, 47.2515 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Epagny Annecy" }, "geometry": { "type": "Point", "coordinates": [ 6.08338, 45.92898 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "CROLLES" }, "geometry": { "type": "Point", "coordinates": [ 5.8900614, 45.2696081 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Loiret" }, "geometry": { "type": "Point", "coordinates": [ 1.9236, 47.913 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Le Port Marly" }, "geometry": { "type": "Point", "coordinates": [ 2.1067305, 48.8823058 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Indre Et Loire" }, "geometry": { "type": "Point", "coordinates": [ 0.70649, 47.42956 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Le Pontet" }, "geometry": { "type": "Point", "coordinates": [ 4.8736, 43.9769 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "BIGUGLIA" }, "geometry": { "type": "Point", "coordinates": [ 9.437, 42.6201 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Paris" }, "geometry": { "type": "Point", "coordinates": [ 2.3744, 48.87817 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Puy De Dome" }, "geometry": { "type": "Point", "coordinates": [ 3.1392, 45.7511 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Villeneuve d'Ascq" }, "geometry": { "type": "Point", "coordinates": [ 3.1213209, 50.6342677 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Marseille" }, "geometry": { "type": "Point", "coordinates": [ 5.40321, 43.27807 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Metz" }, "geometry": { "type": "Point", "coordinates": [ 6.1653131, 49.1309621 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "H�rault" }, "geometry": { "type": "Point", "coordinates": [ 3.85026, 43.59685 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Sausheim" }, "geometry": { "type": "Point", "coordinates": [ 7.38033, 47.77723 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Saint Ouen l'Aum�ne" }, "geometry": { "type": "Point", "coordinates": [ 2.11881, 49.03419 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Cesson Sevigne" }, "geometry": { "type": "Point", "coordinates": [ -1.62765, 48.10563 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Saint Maur des Foss�s" }, "geometry": { "type": "Point", "coordinates": [ 2.4707924, 48.8105745 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Bas Rhin" }, "geometry": { "type": "Point", "coordinates": [ 7.7271259, 48.6229974 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Haute Garonne" }, "geometry": { "type": "Point", "coordinates": [ 1.5147265, 43.5476354 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Rouen" }, "geometry": { "type": "Point", "coordinates": [ 1.06696, 49.44903 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "LIEVIN" }, "geometry": { "type": "Point", "coordinates": [ 2.78654, 50.42835 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Paris" }, "geometry": { "type": "Point", "coordinates": [ 2.29649, 48.84959 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Witry-Les-Reims" }, "geometry": { "type": "Point", "coordinates": [ 4.10753, 49.28889 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Annemasse Ville la Grand" }, "geometry": { "type": "Point", "coordinates": [ 6.26707, 46.19981 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Merignac" }, "geometry": { "type": "Point", "coordinates": [ -0.6604166, 44.8324113 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Boulogne-sur-Mer" }, "geometry": { "type": "Point", "coordinates": [ 1.609517, 50.695745 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Paris" }, "geometry": { "type": "Point", "coordinates": [ 2.29333, 48.87472 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Limoges" }, "geometry": { "type": "Point", "coordinates": [ 1.278582, 45.887291 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Beziers" }, "geometry": { "type": "Point", "coordinates": [ 3.25192, 43.34726 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "NOGENT LE PHAYE" }, "geometry": { "type": "Point", "coordinates": [ 1.5460947, 48.4531588 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "FREJUS" }, "geometry": { "type": "Point", "coordinates": [ 6.7340748, 43.4739462 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Charente Maritime" }, "geometry": { "type": "Point", "coordinates": [ -1.1040153, 46.1798792 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "VANNES" }, "geometry": { "type": "Point", "coordinates": [ -2.7856132, 47.6662641 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Nice" }, "geometry": { "type": "Point", "coordinates": [ 7.20111, 43.68888 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "TRELISSAC" }, "geometry": { "type": "Point", "coordinates": [ 0.7898306, 45.1978524 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Pyr�n�es Atlantiques" }, "geometry": { "type": "Point", "coordinates": [ -1.48842, 43.44401 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Dijon" }, "geometry": { "type": "Point", "coordinates": [ 5.02181, 47.28539 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "NIMES" }, "geometry": { "type": "Point", "coordinates": [ 4.34087, 43.813 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Calvados" }, "geometry": { "type": "Point", "coordinates": [ -0.3685, 49.228 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "Maxeville" }, "geometry": { "type": "Point", "coordinates": [ 6.1359, 48.708 ] } },
{ "type": "Feature", "properties": { "Make": "Jaguar", "City": "LANESTER" }, "geometry": { "type": "Point", "coordinates": [ -3.3398, 47.781 ] } }
]
}
