var json_Landrover_8 = {
"type": "FeatureCollection",
"name": "Landrover_8",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Paris" }, "geometry": { "type": "Point", "coordinates": [ 2.2932145, 48.8750888 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Perpignan" }, "geometry": { "type": "Point", "coordinates": [ 2.8957978, 42.671088 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Normanville" }, "geometry": { "type": "Point", "coordinates": [ 1.16307, 49.078291 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Le Port Marly" }, "geometry": { "type": "Point", "coordinates": [ 2.1067305, 48.8823058 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Beziers" }, "geometry": { "type": "Point", "coordinates": [ 3.2520481, 43.3468298 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Paris" }, "geometry": { "type": "Point", "coordinates": [ 2.3745916, 48.8783285 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Chennevieres Sur Marne" }, "geometry": { "type": "Point", "coordinates": [ 2.5393023, 48.7992707 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Villeneuve d'Ascq" }, "geometry": { "type": "Point", "coordinates": [ 3.1227278, 50.6402389 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Meaux" }, "geometry": { "type": "Point", "coordinates": [ 2.9195067, 48.9578064 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Toulouse Ouest" }, "geometry": { "type": "Point", "coordinates": [ 1.4245087, 43.6478311 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Paris" }, "geometry": { "type": "Point", "coordinates": [ 2.2967458, 48.8497836 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Boulogne-sur-Mer" }, "geometry": { "type": "Point", "coordinates": [ 1.613334, 50.725231 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Merignac" }, "geometry": { "type": "Point", "coordinates": [ -0.6609909, 44.8324527 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Le Pontet" }, "geometry": { "type": "Point", "coordinates": [ 4.8736, 43.9769 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "V�nissieux" }, "geometry": { "type": "Point", "coordinates": [ 4.8652926, 45.717525 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "CROLLES" }, "geometry": { "type": "Point", "coordinates": [ 5.8900614, 45.2696081 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Gap" }, "geometry": { "type": "Point", "coordinates": [ 6.0522, 44.54 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "MEZZAVIA" }, "geometry": { "type": "Point", "coordinates": [ 8.774528, 41.952176 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "FREJUS" }, "geometry": { "type": "Point", "coordinates": [ 6.73277, 43.47361 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Le Cannet" }, "geometry": { "type": "Point", "coordinates": [ 7.01234, 43.57559 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Nice" }, "geometry": { "type": "Point", "coordinates": [ 7.20111, 43.68888 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Merignac" }, "geometry": { "type": "Point", "coordinates": [ -0.6703392, 44.844963 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Cesson Sevigne" }, "geometry": { "type": "Point", "coordinates": [ -1.615609, 48.1080154 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Limonest" }, "geometry": { "type": "Point", "coordinates": [ 4.77356, 45.80411 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "CHANTILLY" }, "geometry": { "type": "Point", "coordinates": [ 2.463, 49.2 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Epagny Annecy" }, "geometry": { "type": "Point", "coordinates": [ 6.08338, 45.92898 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "La Ravoire" }, "geometry": { "type": "Point", "coordinates": [ 5.96312, 45.57 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Indre Et Loire" }, "geometry": { "type": "Point", "coordinates": [ 0.70649, 47.42956 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Dury Les Amiens" }, "geometry": { "type": "Point", "coordinates": [ 2.2811074, 49.8747095 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Les Ulis" }, "geometry": { "type": "Point", "coordinates": [ 2.19434, 48.6780836 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Limoges" }, "geometry": { "type": "Point", "coordinates": [ 1.2793815, 45.8882712 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Calvados" }, "geometry": { "type": "Point", "coordinates": [ -0.367226, 49.227617 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Rouen" }, "geometry": { "type": "Point", "coordinates": [ 1.0659275, 49.4471129 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Lot Et Garonne" }, "geometry": { "type": "Point", "coordinates": [ 0.61897, 44.188 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "BIGUGLIA" }, "geometry": { "type": "Point", "coordinates": [ 9.43848, 42.63038 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "NOGENT LE PHAYE" }, "geometry": { "type": "Point", "coordinates": [ 1.545887, 48.451964 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Puy De Dome" }, "geometry": { "type": "Point", "coordinates": [ 3.1370891, 45.7486446 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Dijon" }, "geometry": { "type": "Point", "coordinates": [ 5.0209375, 47.2869602 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Epinal" }, "geometry": { "type": "Point", "coordinates": [ 6.4789229, 48.1754415 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Samoreau" }, "geometry": { "type": "Point", "coordinates": [ 2.7724502, 48.4241028 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Charente Maritime" }, "geometry": { "type": "Point", "coordinates": [ -1.1040153, 46.1798792 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Saone Et Loire" }, "geometry": { "type": "Point", "coordinates": [ 4.84315, 46.33 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Marseille" }, "geometry": { "type": "Point", "coordinates": [ 5.399769, 43.277589 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Metz" }, "geometry": { "type": "Point", "coordinates": [ 6.16559, 49.13019 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "H�rault" }, "geometry": { "type": "Point", "coordinates": [ 3.85026, 43.59685 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Sausheim" }, "geometry": { "type": "Point", "coordinates": [ 7.38033, 47.77723 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Loire Atlantique" }, "geometry": { "type": "Point", "coordinates": [ -1.6228, 47.2515 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Loiret" }, "geometry": { "type": "Point", "coordinates": [ 1.9236, 47.913 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Saint Ouen l'Aum�ne" }, "geometry": { "type": "Point", "coordinates": [ 2.1183682, 49.0337276 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "RODEZ" }, "geometry": { "type": "Point", "coordinates": [ 2.5428, 44.374 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Loire" }, "geometry": { "type": "Point", "coordinates": [ 4.3906756, 45.4484924 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Saint Maur des Foss�s" }, "geometry": { "type": "Point", "coordinates": [ 2.470686, 48.8103914 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Bas Rhin" }, "geometry": { "type": "Point", "coordinates": [ 7.7268112, 48.6230303 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Semeac" }, "geometry": { "type": "Point", "coordinates": [ 0.1144398, 43.2123979 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Haute Garonne" }, "geometry": { "type": "Point", "coordinates": [ 1.513665, 43.547362 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Barberey-Saint-Sulpice" }, "geometry": { "type": "Point", "coordinates": [ 4.0249765, 48.3293646 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Witry-Les-Reims" }, "geometry": { "type": "Point", "coordinates": [ 4.10753, 49.28889 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Annemasse Ville la Grand" }, "geometry": { "type": "Point", "coordinates": [ 6.26707, 46.19981 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "LIEVIN" }, "geometry": { "type": "Point", "coordinates": [ 2.7882008, 50.427752 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Aix En Provence" }, "geometry": { "type": "Point", "coordinates": [ 5.4002148, 43.5076083 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Var" }, "geometry": { "type": "Point", "coordinates": [ 6.0356144, 43.1407279 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Valence" }, "geometry": { "type": "Point", "coordinates": [ 4.93353, 44.9225 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "FRANCE" }, "geometry": { "type": "Point", "coordinates": [ 4.34087, 43.813 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "TRELISSAC" }, "geometry": { "type": "Point", "coordinates": [ 0.7898306, 45.1978524 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Pyr�n�es Atlantiques" }, "geometry": { "type": "Point", "coordinates": [ -1.48842, 43.44401 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "VANNES" }, "geometry": { "type": "Point", "coordinates": [ -2.7913689, 47.6630328 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "BESANCON" }, "geometry": { "type": "Point", "coordinates": [ 5.953, 47.214 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "Maxeville" }, "geometry": { "type": "Point", "coordinates": [ 6.1359, 48.708 ] } },
{ "type": "Feature", "properties": { "Make": "Landrover", "City": "LANESTER" }, "geometry": { "type": "Point", "coordinates": [ -3.3398, 47.781 ] } }
]
}
