var json_MercedesBenz_4 = {
"type": "FeatureCollection",
"name": "MercedesBenz_4",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MONTEVRAIN" }, "geometry": { "type": "Point", "coordinates": [ 2.7548481, 48.853791 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "EPERNAY" }, "geometry": { "type": "Point", "coordinates": [ 3.9521906, 49.0488195 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHARLEVILLE-MEZIERES" }, "geometry": { "type": "Point", "coordinates": [ 4.7380648, 49.7407359 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "DISTR�" }, "geometry": { "type": "Point", "coordinates": [ -0.1309095, 47.2295612 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VILLE LA GRAND" }, "geometry": { "type": "Point", "coordinates": [ 6.2641661, 46.2018434 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-BRIEUC" }, "geometry": { "type": "Point", "coordinates": [ -2.7353978, 48.5076497 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BEGLES" }, "geometry": { "type": "Point", "coordinates": [ -0.5381226, 44.8167809 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "N�MES" }, "geometry": { "type": "Point", "coordinates": [ 4.3556662, 43.8146247 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BISCHHEIM" }, "geometry": { "type": "Point", "coordinates": [ 7.7294212, 48.6184613 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MARSEILLE" }, "geometry": { "type": "Point", "coordinates": [ 5.4227931, 43.2810468 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BONDY" }, "geometry": { "type": "Point", "coordinates": [ 2.4812883, 48.9062736 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VILLEFRANCHE-SUR-SA�NE" }, "geometry": { "type": "Point", "coordinates": [ 4.7386826, 45.9957271 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SISTERON" }, "geometry": { "type": "Point", "coordinates": [ 5.9314396, 44.2080136 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHOLET" }, "geometry": { "type": "Point", "coordinates": [ -0.8461906, 47.0678424 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SILLINGY" }, "geometry": { "type": "Point", "coordinates": [ 6.0719375, 45.9438275 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MORSBACH" }, "geometry": { "type": "Point", "coordinates": [ 6.8772798, 49.1741275 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MEAUX" }, "geometry": { "type": "Point", "coordinates": [ 2.9195067, 48.9578064 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VIRY-CHATILLON" }, "geometry": { "type": "Point", "coordinates": [ 2.377625, 48.6823885 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CAUDAN" }, "geometry": { "type": "Point", "coordinates": [ -3.337632, 47.810755 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "DREUX" }, "geometry": { "type": "Point", "coordinates": [ 1.3557653, 48.7477462 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VERT-SAINT-DENIS" }, "geometry": { "type": "Point", "coordinates": [ 2.628319, 48.5682631 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BELLERIVE-SUR-ALLIER" }, "geometry": { "type": "Point", "coordinates": [ 3.4011841, 46.1257643 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LOISON-SOUS-LENS" }, "geometry": { "type": "Point", "coordinates": [ 2.8634504, 50.4466999 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-AVIT" }, "geometry": { "type": "Point", "coordinates": [ -0.450888, 43.9185877 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MONTROUGE" }, "geometry": { "type": "Point", "coordinates": [ 2.3275277, 48.8173716 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "POITIERS" }, "geometry": { "type": "Point", "coordinates": [ 0.3056716, 46.5533996 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "AVIGNON" }, "geometry": { "type": "Point", "coordinates": [ 4.8361854, 43.9288148 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHAMBRAY-LES-TOURS" }, "geometry": { "type": "Point", "coordinates": [ 0.7068127, 47.3293713 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "FONTENAY-SOUS-BOIS" }, "geometry": { "type": "Point", "coordinates": [ 2.4889407, 48.8604425 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LONGUENESSE" }, "geometry": { "type": "Point", "coordinates": [ 2.2643319, 50.7376312 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BREST" }, "geometry": { "type": "Point", "coordinates": [ -4.4667926, 48.4167385 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CAMBRAI" }, "geometry": { "type": "Point", "coordinates": [ 3.2191434, 50.1757114 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BRIVE-LA-GAILLARDE" }, "geometry": { "type": "Point", "coordinates": [ 1.476206, 45.141554 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHAURAY" }, "geometry": { "type": "Point", "coordinates": [ -0.3778243, 46.3418236 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "ORVAULT" }, "geometry": { "type": "Point", "coordinates": [ -1.619405, 47.274344 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "DIEPPE" }, "geometry": { "type": "Point", "coordinates": [ 1.0892395, 49.9164156 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LE HAVRE" }, "geometry": { "type": "Point", "coordinates": [ 0.1473832, 49.4931209 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHAMPNIERS" }, "geometry": { "type": "Point", "coordinates": [ 0.205213, 45.7148899 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BOURG-EN-BRESSE" }, "geometry": { "type": "Point", "coordinates": [ 5.244646, 46.1878825 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BAYONNE" }, "geometry": { "type": "Point", "coordinates": [ -1.4588246, 43.4930301 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-DENIS" }, "geometry": { "type": "Point", "coordinates": [ 2.3521999, 48.938368 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-QUENTIN" }, "geometry": { "type": "Point", "coordinates": [ 3.2708028, 49.8486316 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MANOSQUE" }, "geometry": { "type": "Point", "coordinates": [ 5.7921713, 43.8208771 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHAMBERY" }, "geometry": { "type": "Point", "coordinates": [ 5.8915074, 45.6071324 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VANNES" }, "geometry": { "type": "Point", "coordinates": [ -2.7864392, 47.665949 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "EVREUX" }, "geometry": { "type": "Point", "coordinates": [ 1.187981, 49.026104 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LE MANS" }, "geometry": { "type": "Point", "coordinates": [ 0.1732222, 47.9762858 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LIMOGES" }, "geometry": { "type": "Point", "coordinates": [ 1.2685469, 45.8683589 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BOULOGNE-BILLANCOURT" }, "geometry": { "type": "Point", "coordinates": [ 2.2479832, 48.8392018 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-LOUP-DE-VARENNES" }, "geometry": { "type": "Point", "coordinates": [ 4.8657676, 46.7110731 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MERIGNAC" }, "geometry": { "type": "Point", "coordinates": [ -0.6678661, 44.8471768 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "RUEIL-MALMAISON" }, "geometry": { "type": "Point", "coordinates": [ 2.1569216, 48.8696585 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "RAMBOUILLET" }, "geometry": { "type": "Point", "coordinates": [ 1.8226705, 48.6257285 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "TOURLAVILLE" }, "geometry": { "type": "Point", "coordinates": [ -1.5823494, 49.6331759 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "AURILLAC" }, "geometry": { "type": "Point", "coordinates": [ 2.458826, 44.9144336 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "NARBONNE" }, "geometry": { "type": "Point", "coordinates": [ 2.986285, 43.1627489 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-MALO" }, "geometry": { "type": "Point", "coordinates": [ -1.9871617, 48.6249988 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LAXOU" }, "geometry": { "type": "Point", "coordinates": [ 6.1300423, 48.6920688 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "AIX-EN-PROVENCE" }, "geometry": { "type": "Point", "coordinates": [ 5.4360561, 43.5271628 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "EPINAL" }, "geometry": { "type": "Point", "coordinates": [ 6.4736255, 48.1859245 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHEN�VE" }, "geometry": { "type": "Point", "coordinates": [ 5.0154376, 47.2843052 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "GLOS" }, "geometry": { "type": "Point", "coordinates": [ 0.2204203, 49.1446952 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHAMPS-SUR-MARNE" }, "geometry": { "type": "Point", "coordinates": [ 2.5842441, 48.8492505 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SENS" }, "geometry": { "type": "Point", "coordinates": [ 3.2759458, 48.2086983 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CASTRES" }, "geometry": { "type": "Point", "coordinates": [ 2.1958635, 43.5899914 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SANC�" }, "geometry": { "type": "Point", "coordinates": [ 4.8442126, 46.3373125 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "RIVERY" }, "geometry": { "type": "Point", "coordinates": [ 2.3396701, 49.9125021 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-ETIENNE" }, "geometry": { "type": "Point", "coordinates": [ 4.3883356, 45.4582268 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BUCHERES" }, "geometry": { "type": "Point", "coordinates": [ 4.1035662, 48.2467912 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SOISSONS" }, "geometry": { "type": "Point", "coordinates": [ 3.3363658, 49.3713345 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-MAXIMIN" }, "geometry": { "type": "Point", "coordinates": [ 2.4519317, 49.2215032 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "FONTANIL-CORNILLON" }, "geometry": { "type": "Point", "coordinates": [ 5.6578128, 45.2449967 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LES ULIS" }, "geometry": { "type": "Point", "coordinates": [ 2.195243, 48.6846378 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "REIMS" }, "geometry": { "type": "Point", "coordinates": [ 4.021208, 49.2212649 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VILLENEUVE-LOUBET" }, "geometry": { "type": "Point", "coordinates": [ 7.1320076, 43.6381988 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VITROLLES" }, "geometry": { "type": "Point", "coordinates": [ 5.249703, 43.458598 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-FONS" }, "geometry": { "type": "Point", "coordinates": [ 4.8540784, 45.7144105 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "ROQUEBRUNE-SUR-ARGENS" }, "geometry": { "type": "Point", "coordinates": [ 6.63779, 43.461185 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "GIERES" }, "geometry": { "type": "Point", "coordinates": [ 5.779593, 45.187447 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "GAP" }, "geometry": { "type": "Point", "coordinates": [ 6.0963221, 44.5667738 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "ROYAN" }, "geometry": { "type": "Point", "coordinates": [ -0.9977984, 45.6271224 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BONNEUIL-SUR-MARNE" }, "geometry": { "type": "Point", "coordinates": [ 2.4906184, 48.7712659 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "FLEURY-LES-AUBRAIS" }, "geometry": { "type": "Point", "coordinates": [ 1.9011766, 47.9251864 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-MEMMIE" }, "geometry": { "type": "Point", "coordinates": [ 4.3932424, 48.9484083 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "ALBI" }, "geometry": { "type": "Point", "coordinates": [ 2.1433983, 43.912858 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LA-CHAUSSEE-ST-VICTOR" }, "geometry": { "type": "Point", "coordinates": [ 1.3551089, 47.6125789 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "NICE" }, "geometry": { "type": "Point", "coordinates": [ 7.2561304, 43.7039271 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VALENTON" }, "geometry": { "type": "Point", "coordinates": [ 2.4410779, 48.7677079 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "INGERSHEIM" }, "geometry": { "type": "Point", "coordinates": [ 7.3160661, 48.091547 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LYON" }, "geometry": { "type": "Point", "coordinates": [ 4.7973945, 45.775974 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-GREGOIRE" }, "geometry": { "type": "Point", "coordinates": [ -1.6916441, 48.1379227 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "TARBES" }, "geometry": { "type": "Point", "coordinates": [ 0.0842342, 43.2192399 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "QUIMPER" }, "geometry": { "type": "Point", "coordinates": [ -4.097899, 47.997542 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SERMOISE SUR LOIRE" }, "geometry": { "type": "Point", "coordinates": [ 3.1578856, 46.9636236 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "ROANNE" }, "geometry": { "type": "Point", "coordinates": [ 4.0850923, 46.0448437 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "ROUEN" }, "geometry": { "type": "Point", "coordinates": [ 1.0712744, 49.4479588 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "ARLES" }, "geometry": { "type": "Point", "coordinates": [ 4.6421776, 43.7038774 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "COMPIEGNE" }, "geometry": { "type": "Point", "coordinates": [ 2.787544, 49.391327 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LESCAR" }, "geometry": { "type": "Point", "coordinates": [ -0.4229186, 43.3205571 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SALLERTAINE" }, "geometry": { "type": "Point", "coordinates": [ -1.8919591, 46.8572318 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MARSEILLE" }, "geometry": { "type": "Point", "coordinates": [ 5.4725237, 43.2958988 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BELLEVILLE-SUR-VIE" }, "geometry": { "type": "Point", "coordinates": [ -1.4321239, 46.7855067 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "THILLOIS" }, "geometry": { "type": "Point", "coordinates": [ 3.961874, 49.254564 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SARROLA CARCOPINO" }, "geometry": { "type": "Point", "coordinates": [ 8.8433, 42.0286 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "GU�RANDE" }, "geometry": { "type": "Point", "coordinates": [ -2.408432, 47.3087286 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-VINCENT DE PAUL" }, "geometry": { "type": "Point", "coordinates": [ -1.015993, 43.7417159 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHATEAUROUX" }, "geometry": { "type": "Point", "coordinates": [ 1.714602, 46.804104 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MONDEVILLE" }, "geometry": { "type": "Point", "coordinates": [ -0.3160948, 49.1674521 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CAHORS" }, "geometry": { "type": "Point", "coordinates": [ 1.4392093, 44.42075 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BONCHAMP-LES-LAVAL" }, "geometry": { "type": "Point", "coordinates": [ -0.700079, 48.073661 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "AUCH" }, "geometry": { "type": "Point", "coordinates": [ 0.586709, 43.64638 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VILLEV�QUE" }, "geometry": { "type": "Point", "coordinates": [ -0.4318772, 47.5203398 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VALENCE" }, "geometry": { "type": "Point", "coordinates": [ 4.9341055, 44.9145548 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MURET" }, "geometry": { "type": "Point", "coordinates": [ 1.3348306, 43.4831117 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "PUILBOREAU" }, "geometry": { "type": "Point", "coordinates": [ -1.1084207, 46.1769204 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BEAUVAIS" }, "geometry": { "type": "Point", "coordinates": [ 2.1176392, 49.4276383 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-MARTIN-DES-CHAMPS" }, "geometry": { "type": "Point", "coordinates": [ -3.8619787, 48.5787243 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VESOUL" }, "geometry": { "type": "Point", "coordinates": [ 6.15428, 47.619788 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-GERMAIN-LAPRADE" }, "geometry": { "type": "Point", "coordinates": [ 3.951885, 45.052068 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "ISQUES" }, "geometry": { "type": "Point", "coordinates": [ 1.65628, 50.678993 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "REZ�" }, "geometry": { "type": "Point", "coordinates": [ -1.5401017, 47.1565208 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "PARIS" }, "geometry": { "type": "Point", "coordinates": [ 2.3687358, 48.847419 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MONTELIMAR" }, "geometry": { "type": "Point", "coordinates": [ 4.7460199, 44.5774915 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "PARIS" }, "geometry": { "type": "Point", "coordinates": [ 2.2980955, 48.8820088 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "AUBIERE" }, "geometry": { "type": "Point", "coordinates": [ 3.1343226, 45.7502688 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LA TESTE DE BUCH" }, "geometry": { "type": "Point", "coordinates": [ -1.1199395, 44.6113481 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CARCASSONNE" }, "geometry": { "type": "Point", "coordinates": [ 2.3080561, 43.2034545 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MESSIA-SUR-SORNE" }, "geometry": { "type": "Point", "coordinates": [ 5.5182301, 46.6601171 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VALENCIENNES" }, "geometry": { "type": "Point", "coordinates": [ 3.5164453, 50.3446072 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "TERVILLE" }, "geometry": { "type": "Point", "coordinates": [ 6.143239, 49.348793 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MONTAUBAN" }, "geometry": { "type": "Point", "coordinates": [ 1.335458, 43.97702 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "ONET LE CHATEAU" }, "geometry": { "type": "Point", "coordinates": [ 2.585786, 44.371674 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-DOULCHARD" }, "geometry": { "type": "Point", "coordinates": [ 2.3764962, 47.1204543 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CARENTAN" }, "geometry": { "type": "Point", "coordinates": [ -1.2555031, 49.3100473 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BOULOGNE-BILLANCOURT" }, "geometry": { "type": "Point", "coordinates": [ 2.24633, 48.834641 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAINT-OUEN-L'AUMONE" }, "geometry": { "type": "Point", "coordinates": [ 2.1207951, 49.0353457 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "FONTENAY-SUR-EURE" }, "geometry": { "type": "Point", "coordinates": [ 1.4467107, 48.419383 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MAGNANVILLE" }, "geometry": { "type": "Point", "coordinates": [ 1.685237, 48.970357 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "ECOLE-VALENTIN" }, "geometry": { "type": "Point", "coordinates": [ 5.9906559, 47.2770175 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "PERRIGNY" }, "geometry": { "type": "Point", "coordinates": [ 3.55598, 47.816906 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "DENNEY" }, "geometry": { "type": "Point", "coordinates": [ 6.8985679, 47.6541799 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CLUSES" }, "geometry": { "type": "Point", "coordinates": [ 6.598064, 46.0480052 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "TOULOUSE" }, "geometry": { "type": "Point", "coordinates": [ 1.468331, 43.644249 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LE PASSAGE D'AGEN" }, "geometry": { "type": "Point", "coordinates": [ 0.612107, 44.165749 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VILLENEUVE-LES-B�ZIERS" }, "geometry": { "type": "Point", "coordinates": [ 3.3078439, 43.321258 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "MONTLU�ON" }, "geometry": { "type": "Point", "coordinates": [ 2.5965884, 46.3500773 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CERIS�" }, "geometry": { "type": "Point", "coordinates": [ 0.117047, 48.4484938 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHATEAUBERNARD" }, "geometry": { "type": "Point", "coordinates": [ -0.3260274, 45.693985 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "TRELISSAC" }, "geometry": { "type": "Point", "coordinates": [ 0.7936817, 45.1999233 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LAMBRES-LEZ-DOUAI" }, "geometry": { "type": "Point", "coordinates": [ 3.089342, 50.347786 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CHATEAU D'OLONNE" }, "geometry": { "type": "Point", "coordinates": [ -1.753944, 46.498737 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "VILLENEUVE-D'ASCQ" }, "geometry": { "type": "Point", "coordinates": [ 3.124783, 50.643536 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "CASTELNAU-LE-LEZ" }, "geometry": { "type": "Point", "coordinates": [ 3.925555, 43.638054 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "TOURNON-FRONTENEX" }, "geometry": { "type": "Point", "coordinates": [ 6.330275, 45.639641 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "PARIS" }, "geometry": { "type": "Point", "coordinates": [ 2.2843126, 48.865536 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "DUNKERQUE" }, "geometry": { "type": "Point", "coordinates": [ 2.360578, 51.017998 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LE CANNET" }, "geometry": { "type": "Point", "coordinates": [ 7.0124339, 43.5740299 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SABL�-SUR-SARTHE" }, "geometry": { "type": "Point", "coordinates": [ -0.307978, 47.831215 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "PERPIGNAN" }, "geometry": { "type": "Point", "coordinates": [ 2.8937474, 42.6774369 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "TRAPPES" }, "geometry": { "type": "Point", "coordinates": [ 1.9903816, 48.7720188 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LE CHESNAY" }, "geometry": { "type": "Point", "coordinates": [ 2.1161811, 48.8279664 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SAUSHEIM" }, "geometry": { "type": "Point", "coordinates": [ 7.379077, 47.779128 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SALON-DE-PROVENCE" }, "geometry": { "type": "Point", "coordinates": [ 5.087717, 43.623463 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "LA GARDE" }, "geometry": { "type": "Point", "coordinates": [ 6.029109, 43.136185 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "BEAURAINS" }, "geometry": { "type": "Point", "coordinates": [ 2.795453, 50.263638 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "COLOMBES" }, "geometry": { "type": "Point", "coordinates": [ 2.2525362, 48.9159987 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "AVERMES" }, "geometry": { "type": "Point", "coordinates": [ 3.303575, 46.602348 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "SEYSSUEL" }, "geometry": { "type": "Point", "coordinates": [ 4.8357872, 45.547881 ] } },
{ "type": "Feature", "properties": { "Make": "Mercedes-Benz", "City": "METZ" }, "geometry": { "type": "Point", "coordinates": [ 6.2412308, 49.1076674 ] } }
]
}
