var json_Volvo_2 = {
"type": "FeatureCollection",
"name": "Volvo_2",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "ORL�ANS" }, "geometry": { "type": "Point", "coordinates": [ 1.9239287, 47.9146777 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "NIORT" }, "geometry": { "type": "Point", "coordinates": [ -0.47429, 46.3152 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "REDON" }, "geometry": { "type": "Point", "coordinates": [ -2.0880119, 47.6480257 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CHENNEVI�RES" }, "geometry": { "type": "Point", "coordinates": [ 2.5474888, 48.797137 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LIMOGES" }, "geometry": { "type": "Point", "coordinates": [ 1.2868883, 45.8185234 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "REIMS" }, "geometry": { "type": "Point", "coordinates": [ 4.0848617, 49.236434 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "METZ" }, "geometry": { "type": "Point", "coordinates": [ 6.1652725, 49.1416401 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "BREST" }, "geometry": { "type": "Point", "coordinates": [ -4.4673123, 48.4152194 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LE HAVRE" }, "geometry": { "type": "Point", "coordinates": [ 0.1477176, 49.4952875 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "GONESSE" }, "geometry": { "type": "Point", "coordinates": [ 2.419616, 48.997299 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LA ROCHELLE" }, "geometry": { "type": "Point", "coordinates": [ -1.1176964, 46.1540778 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "VALENCE" }, "geometry": { "type": "Point", "coordinates": [ 4.8815519, 44.9000553 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "VERSAILLES" }, "geometry": { "type": "Point", "coordinates": [ 2.1412131, 48.7945013 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "AUXERRE" }, "geometry": { "type": "Point", "coordinates": [ 3.5724244, 47.8117339 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "MAUREPAS" }, "geometry": { "type": "Point", "coordinates": [ 1.9176891, 48.7585119 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "TOULON" }, "geometry": { "type": "Point", "coordinates": [ 6.034394, 43.139648 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "THEIX VANNES" }, "geometry": { "type": "Point", "coordinates": [ -2.760847, 47.658236 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "ROUEN" }, "geometry": { "type": "Point", "coordinates": [ 1.0667896, 49.4483561 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LORMONT" }, "geometry": { "type": "Point", "coordinates": [ -0.5146459, 44.8799828 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "MARSEILLE" }, "geometry": { "type": "Point", "coordinates": [ 5.3898257, 43.2577246 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LE MANS" }, "geometry": { "type": "Point", "coordinates": [ 0.1971772, 47.9909521 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LES ULIS" }, "geometry": { "type": "Point", "coordinates": [ 2.16647, 48.6792779 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CHOLET" }, "geometry": { "type": "Point", "coordinates": [ -0.9168514, 47.0312286 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "THIONVILLE" }, "geometry": { "type": "Point", "coordinates": [ 6.1599195, 49.3414264 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CANNES" }, "geometry": { "type": "Point", "coordinates": [ 7.0096712, 43.5842944 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "AGEN" }, "geometry": { "type": "Point", "coordinates": [ 0.6321645, 44.17731 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "AVON FONTAINEBLEAU" }, "geometry": { "type": "Point", "coordinates": [ 2.7291659, 48.4180106 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "MONTROUGE" }, "geometry": { "type": "Point", "coordinates": [ 2.326834, 48.8157404 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LORIENT" }, "geometry": { "type": "Point", "coordinates": [ -3.34742, 47.76782 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "QUIMPER" }, "geometry": { "type": "Point", "coordinates": [ -4.02944, 47.99563 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "TROYES" }, "geometry": { "type": "Point", "coordinates": [ 4.0247795, 48.328377 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "ANNEMASSE" }, "geometry": { "type": "Point", "coordinates": [ 6.267217, 46.1998138 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "BOURGES" }, "geometry": { "type": "Point", "coordinates": [ 2.4156222, 47.1113264 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "AVIGNON" }, "geometry": { "type": "Point", "coordinates": [ 4.871739, 43.9177437 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "RODEZ" }, "geometry": { "type": "Point", "coordinates": [ 2.583386, 44.369249 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "RENNES" }, "geometry": { "type": "Point", "coordinates": [ -1.615333, 48.108585 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CARCASSONNE" }, "geometry": { "type": "Point", "coordinates": [ 2.30375051, 43.20663 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "NIMES" }, "geometry": { "type": "Point", "coordinates": [ 4.3269593, 43.8078985 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LILLE" }, "geometry": { "type": "Point", "coordinates": [ 3.1290836, 50.7511319 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CAEN" }, "geometry": { "type": "Point", "coordinates": [ -0.37, 49.227 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "SOUFFELWEYERSHEIM (STRASBOURG)" }, "geometry": { "type": "Point", "coordinates": [ 7.7268112, 48.6230303 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "DECHY" }, "geometry": { "type": "Point", "coordinates": [ 3.119499, 50.3444977 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "RIVERY LES AMIENS" }, "geometry": { "type": "Point", "coordinates": [ 2.3381633, 49.9167669 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "�PINAY-SUR-SEINE" }, "geometry": { "type": "Point", "coordinates": [ 2.3081991, 48.9582471 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "SAINT-OUEN-L'AUM�NE" }, "geometry": { "type": "Point", "coordinates": [ 2.12252855, 49.0359268 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "PARIS (16�me)" }, "geometry": { "type": "Point", "coordinates": [ 2.2740828, 48.8479979 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "NEUILLY-SUR-SEINE" }, "geometry": { "type": "Point", "coordinates": [ 2.2728894, 48.8812988 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "PORT-MARLY" }, "geometry": { "type": "Point", "coordinates": [ 2.1083741, 48.8819075 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LA GARENNE-COLOMBES" }, "geometry": { "type": "Point", "coordinates": [ 2.2575455, 48.9060349 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "SAINTES" }, "geometry": { "type": "Point", "coordinates": [ -0.654628, 45.7405685 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LA ROCHE-SUR-YON" }, "geometry": { "type": "Point", "coordinates": [ -1.4281566, 46.7139387 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "TOURLAVILLE (CHERBOURG)" }, "geometry": { "type": "Point", "coordinates": [ -1.58273, 49.6333 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CHARLEVILLE-M�ZI�RES" }, "geometry": { "type": "Point", "coordinates": [ 4.699283, 49.7386131 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "�PAGNY (ANNECY)" }, "geometry": { "type": "Point", "coordinates": [ 6.088606, 45.9243 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "ANGLET (BAYONNE)" }, "geometry": { "type": "Point", "coordinates": [ -1.4983631, 43.4666964 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "�PERNAY" }, "geometry": { "type": "Point", "coordinates": [ 3.9603009, 49.0633002 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "PARIS (11�me)" }, "geometry": { "type": "Point", "coordinates": [ 2.3717498, 48.8598993 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "ALBI" }, "geometry": { "type": "Point", "coordinates": [ 2.1496433, 43.9420041 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CLERMONT-FERRAND" }, "geometry": { "type": "Point", "coordinates": [ 3.13644648, 45.74875 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "ATHIS-MONS" }, "geometry": { "type": "Point", "coordinates": [ 2.37163, 48.70337 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "FR�JUS" }, "geometry": { "type": "Point", "coordinates": [ 6.719809, 43.4381 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "SAUSHEIM (MULHOUSE)" }, "geometry": { "type": "Point", "coordinates": [ 7.3698, 47.78851 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "SAINT-BRIEUC" }, "geometry": { "type": "Point", "coordinates": [ -2.74015, 48.501778 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CH�LONS-EN-CHAMPAGNE" }, "geometry": { "type": "Point", "coordinates": [ 4.354998, 48.981016 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CHAMPNIERS (ANGOUL�ME)" }, "geometry": { "type": "Point", "coordinates": [ 0.173247, 45.689486 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "�PINAL" }, "geometry": { "type": "Point", "coordinates": [ 6.479028, 48.175433 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "GU�RANDE" }, "geometry": { "type": "Point", "coordinates": [ -2.4131472, 47.3215076 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "MAX�VILLE" }, "geometry": { "type": "Point", "coordinates": [ 6.13582, 48.708 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CHANTILLY" }, "geometry": { "type": "Point", "coordinates": [ 2.46221, 49.19484 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "BOURG-EN-BRESSE" }, "geometry": { "type": "Point", "coordinates": [ 5.2319706, 46.2256125 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "BUCHELAY (MANTES-LA-JOLIE)" }, "geometry": { "type": "Point", "coordinates": [ 1.67738, 48.99058 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "POITIERS" }, "geometry": { "type": "Point", "coordinates": [ 0.3142578, 46.5794613 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "PERPIGNAN" }, "geometry": { "type": "Point", "coordinates": [ 2.893534, 42.67265 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "NICE" }, "geometry": { "type": "Point", "coordinates": [ 7.199151, 43.68222 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "TARBES" }, "geometry": { "type": "Point", "coordinates": [ 0.1056399, 43.2211307 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "AFA (AJACCIO)" }, "geometry": { "type": "Point", "coordinates": [ 8.8058493, 41.9605816 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "MONT-DE-MARSAN" }, "geometry": { "type": "Point", "coordinates": [ -0.44333, 43.92278 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "MELUN" }, "geometry": { "type": "Point", "coordinates": [ 2.6340048, 48.5615583 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "MONTEVRAIN" }, "geometry": { "type": "Point", "coordinates": [ 2.756699, 48.85251 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "MONTPELLIER" }, "geometry": { "type": "Point", "coordinates": [ 3.93397, 43.58855 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "COLMAR" }, "geometry": { "type": "Point", "coordinates": [ 7.3668564, 48.0957185 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LYON SUD" }, "geometry": { "type": "Point", "coordinates": [ 4.872034, 45.71926 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "VILLEFRANCHE-SUR-SA�NE" }, "geometry": { "type": "Point", "coordinates": [ 4.742618, 45.9918 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LYON NORD" }, "geometry": { "type": "Point", "coordinates": [ 4.7978505, 45.7764041 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "GRENOBLE" }, "geometry": { "type": "Point", "coordinates": [ 5.69262, 45.17867 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "SAINT-�TIENNE" }, "geometry": { "type": "Point", "coordinates": [ 4.3906756, 45.4484924 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "VILLENEUVE D'ASCQ" }, "geometry": { "type": "Point", "coordinates": [ 3.12025, 50.63256 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "VALENCIENNES" }, "geometry": { "type": "Point", "coordinates": [ 3.513634, 50.33812 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "NANTES" }, "geometry": { "type": "Point", "coordinates": [ -1.63148, 47.256072 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "SAINT-QUENTIN" }, "geometry": { "type": "Point", "coordinates": [ 3.25112, 49.85084 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "NOGENT-LE-PHAYE (CHARTRES)" }, "geometry": { "type": "Point", "coordinates": [ 1.545, 48.4521 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "NORMANVILLE (EVREUX)" }, "geometry": { "type": "Point", "coordinates": [ 1.1674, 49.0481 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LISIEUX" }, "geometry": { "type": "Point", "coordinates": [ 0.2186898, 49.168828 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "M�CON (SANCE)" }, "geometry": { "type": "Point", "coordinates": [ 4.84381, 46.33332 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CHALONS-SUR-SA�NE" }, "geometry": { "type": "Point", "coordinates": [ 4.8626485, 46.7691988 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CHEN�VE (DIJON)" }, "geometry": { "type": "Point", "coordinates": [ 5.0206131, 47.2858574 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "P�RIGUEUX" }, "geometry": { "type": "Point", "coordinates": [ 0.77, 45.19 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "BRIVE-LA-GAILLARDE" }, "geometry": { "type": "Point", "coordinates": [ 1.484206, 45.13973 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CHAMB�RY" }, "geometry": { "type": "Point", "coordinates": [ 5.96517, 45.56691 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "PERRIGNY (LONS-LE-SAUNIER)" }, "geometry": { "type": "Point", "coordinates": [ 5.575481, 46.66846 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "AIX-EN-PROVENCE" }, "geometry": { "type": "Point", "coordinates": [ 5.4213476, 43.5119131 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "ALENCON" }, "geometry": { "type": "Point", "coordinates": [ 0.114226, 48.44594 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "DUNKERQUE" }, "geometry": { "type": "Point", "coordinates": [ 2.3595412, 51.0217185 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "ANGERS" }, "geometry": { "type": "Point", "coordinates": [ -0.5402673, 47.4512836 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "TOURS" }, "geometry": { "type": "Point", "coordinates": [ 0.6719759, 47.4312798 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "CALAIS" }, "geometry": { "type": "Point", "coordinates": [ 1.8599785, 50.9373626 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "PAU" }, "geometry": { "type": "Point", "coordinates": [ -0.4411771, 43.3235237 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "MERIGNAC" }, "geometry": { "type": "Point", "coordinates": [ -0.673039, 44.831214 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "BESAN�ON" }, "geometry": { "type": "Point", "coordinates": [ 5.9536781, 47.215374 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "LI�VIN" }, "geometry": { "type": "Point", "coordinates": [ 2.7881716, 50.4267878 ] } },
{ "type": "Feature", "properties": { "Make": "Volvo", "City": "TOULOUSE" }, "geometry": { "type": "Point", "coordinates": [ 1.51957, 43.544319 ] } }
]
}
